[workspace]
members = [
	"ranges",
	"lru",
	"calc",
	"server",
	"fibonacci",
	"robot",
	"recursion_worker",
	"trains",
	"postfix_csv",
	"zip",
	"redis",
	"dtmf",
	"visreq",
	"vpn",
	"fizzbuzz",
	"hungarian_snake",
	"epoch",
	"parens",
	"compression",
	"binary",
	"json",
	"sum",
	"base64",
]
resolver = "3"